"""empty message

Revision ID: 5145159bc226
Revises: c319524bd9eb
Create Date: 2023-06-04 00:14:31.223684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5145159bc226'
down_revision = 'c319524bd9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_raw', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('receive_comments_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receive_follow_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('receive_collect_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('show_collections', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('show_collections')
        batch_op.drop_column('receive_collect_notifications')
        batch_op.drop_column('receive_follow_notifications')
        batch_op.drop_column('receive_comments_notifications')
        batch_op.drop_column('avatar_raw')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    op.drop_table('notification')
    # ### end Alembic commands ###
